### ISSUE TITLE
Keine Raw Generics benutzen

### ISSUE THREAD

**Issue by matthias-mueller** [avolar133/FTP-2-CSV#4]
Insbesondere hier:

https://github.com/avolar133/FTP-2-CSV/blob/e6d442bd2b805c96a32bdc39f285d911d982303f/src/main/java/myPackage/LineFormat.java#L13

DIe TreeMap wird ungetypt instanziiert.

**Comment by avolar133** [comment]
Derzeit läuft das Code ohne Map.
